// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZQFnVSPhmGIO16yiiIjk62ZZV_hcWPV0',
    appId: '1:999931607261:web:21ee6381d77c97c2bf4334',
    messagingSenderId: '999931607261',
    projectId: 'luma-a75c4',
    authDomain: 'luma-a75c4.firebaseapp.com',
    storageBucket: 'luma-a75c4.firebasestorage.app',
    measurementId: 'G-HD6SE0BR3V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlSZoXFxwyyorFS4eEMB1ZKisWHpN2g5c',
    appId: '1:999931607261:android:a6f7fc339127e563bf4334',
    messagingSenderId: '999931607261',
    projectId: 'luma-a75c4',
    storageBucket: 'luma-a75c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGFMbr59FlklE-F2Rw8AGApofHtGReH4',
    appId: '1:999931607261:ios:24e1e80c68c597ebbf4334',
    messagingSenderId: '999931607261',
    projectId: 'luma-a75c4',
    storageBucket: 'luma-a75c4.firebasestorage.app',
    iosBundleId: 'com.example.luma',
  );
}
